# Generated by Django 4.2.4 on 2023-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
