# Generated by Django 4.2.4 on 2023-08-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_contact_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Contact',
            new_name='contact',
        ),
    ]
