# Generated by Django 4.2.4 on 2023-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_contact_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
